#!/bin/bash
# Arjienx DNSTT Termux Script Installer
#--------------------------------

rm -rf install

apt-get update
apt-get install -y dnsutils nano

wget --no-check-certificate -O ../usr/bin/admin https://raw.githubusercontent.com/Ysilven/termux-script/main/menu && chmod +x ../usr/bin/menu

echo "Installation Completed."
echo
echo "Arjienx DNSTT Script v0.2.5"
echo "https://phcorner.net/members/arjienx.1773652/"
echo
echo "Arjienx-PHC"
echo "press 'enter' to back and start query testing instantly."
echo "type 'admin' to run the dnstt termux script."
